spring:
  datasource: 
    url: jdbc:mysql://dayrecord.ctizjtx2utrj.ap-northeast-2.rds.amazonaws.com:3306/DayRecord
    username: dayrecord
    password: dayrecord!!^^
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret:
    issuer:
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  mail:
    host: test
    username: user
    password: password
    protocol: smtp
    port: 465

server: