spring:
  datasource: 
    url: jdbc:mariadb://database-1.cra6qigkgda2.ap-northeast-2.rds.amazonaws.com:3306/drone
    username: admin
    password: Ruddnjs0706!
    driver-class-name: org.mariadb.jdbc.Driver
  jwt:
    secret:
    issuer:
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

server: